name: Go

on:
  push:
    tags:
      - '0.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Generate Version
      run: echo "${{github.ref_name}}+$(git rev-parse --short HEAD)" > .version

    - name: Build
      run: make clean && make test

    - name: Build
      run: make

    - name: Publish binaries
      uses: actions/upload-artifact@v2
      with:
        name: aws2fa
        path: build/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/aws2fa-darwin-amd64
        asset_name: aws2fa-darwin-amd64
        asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/aws2fa-linux-amd64
        asset_name: aws2fa-linux-amd64
        asset_content_type: application/octet-stream

#     - name: Test
#       run: go test -v ./...
